### ISSUE TITLE
Its name is Gutenberg

### ISSUE THREAD

**Issue by szepeviktor** [pixelcollective/tiny-container#1]
Hello!

Could you call "WordPress 5 block editor" **Gutenberg editor**?

**Comment by kellymears** [comment]
Gutenberg is just a project name -- the product itself is not called Gutenberg. 

It's actually just the "WordPress editor" now, although I imagine popularly it's called the "new WordPress editor" by some vast majority of WordPress users (most of whom have never even heard "project Gutenberg", except maybe in passing). 

Eventually, once the dust has settled, pretty much everyone will just think of it as "the WordPress editor", for better and worse.

**Comment by szepeviktor** [comment]
Okay I see.

I thought tinyblocks/container is for *technical audience*.
